// src/app/services/smartphone.service.ts


import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Smartphone } from '../models/smartphone.model';

@Injectable({
  providedIn: 'root'
})
export class SmartphoneService {

  private allSmartphones: Smartphone[] = [
    new Smartphone({
      id: 'a40',
      nome: 'OPPO A40',
      imagem: 'assets/img/a40.png',
      subtitulo: '8GB RAM (4+4) | 256GB Armazenamento',
      diferencial: 'Ultra resistência MIL-STD 810H',
      cameras: 'Traseira 50MP, Frontal 5MP',
      carregador: '45W SUPERVOOC',
      bateria: '5100mAh',
      processador: 'Qualcomm® Snapdragon™ 6s gen 1',
      linha: 'linha-a',
      specs: {
        cores: 'Vinho | Lilás',
        dimensoesPeso: { altura: 'aprox. 165.77mm', largura: 'aprox. 76.08mm', espessura: 'aprox. 7.68mm', peso: 'aprox. 186g' },
        armazenamento: { ram: '8GB (4+4)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'eMMC 5.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.67”', proporcaoTela: '89.9%', resolucao: 'HD+ (1604 x 720)', taxaAtualizacao: '90Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 83% NTSC | Modo Conforto: 71% NTSC', profundidadeCor: '16.7 milhões de cores (8-bit)', densidadePixels: '264 PPI', brilho: 'Pico: 1000nits', painel: 'LCD', coberturaVidro: 'China Southern Glass (duas vezes reforçado) | Panda (duas vezes reforçado)' },
        cameras: { traseira: '50MP', frontal: '5MP', modoDisparo: { traseira: 'Pro, Vídeo, Foto, Noite, Panorâmica, Slow motion, Time-lapse, Adesivo, Scanner de Texto, e Extra HD | Principal: 50MP; f/1.8; FOV 76°; Lente 5P; AF; motor de foco open-loop | Sensor Flicker: 2MP', frontal: 'Vídeo, Foto, Retrato, Noite, Panorâmica, Time-lapse, Adesivo, e Extra HD | 5MP; f/2.2, FOV 78°; Lente 3P; FF' }, video: { traseira: '1080P - 30fps, 720P - 30fps | Modo Time-lapse: 1080P - 30fps', frontal: 'Até 1080 - 30fps, 720P - 30fps por padrão' } },
        processamento: { soc: 'Qualcomm® Snapdragon™ 6s gen 1', cpu: 'octa-core', gpu: 'Adreno™ 610 - 1050MHz' },
        bateria: { capacidade: '5100mAh', carregamentoRapido: '45W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Não suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade', 'Pedômetro'],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/26/28 | LTE TDD: 38/40/41 | 4G móvel' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz', versaoBluetooth: 'Bluetooth® 5.0, BLE', codecAudioBluetooth: 'SBC, AAC, aptx', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Não suportado' },
        sistemaOperacional: 'ColorOS 14.0 (Baseado em Android 14)',
        tecnologiaLocalizacao: { gnss: 'BeiDou, GPS, GLONASS, Galileo e QZSS', outros: 'Single frequency: Positioning with A-GNSS, WLAN, and cellular data' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'a5versao4g',
      nome: 'OPPO A5 4G',
      imagem: 'assets/img/a5versao4g.png',
      subtitulo: '12GB RAM (6+6) | 256GB Armazenamento',
      diferencial: 'Ultra resistência MIL-STD 810H | Câmera com IA',
      cameras: 'Traseira 50MP, Frontal 5MP',
      carregador: '45W SUPERVOOC',
      bateria: '6000mAh',
      processador: 'Qualcomm® Snapdragon™ 6s gen 1',
      linha: 'linha-a',
      specs: {
        cores: 'Branco | Roxo',
        dimensoesPeso: { altura: 'aprox. 165,71mm', largura: 'aprox. 76,24mm', espessura: 'aprox. 7,99mm', peso: 'cerca de 193g' },
        armazenamento: { ram: '12GB (6+6)', tipoRam: 'LPDDR4x', rom: '256GB', especificacoesRom: 'UFS 2.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6,67"', proporcaoTela: '89.9%', resolucao: 'HD+ (1604 x 720)', taxaAtualizacao: '90Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 83% DCI-P3 | Modo Natural: 71% sRGB', profundidadeCor: '16,7 milhões de cores (8-bit)', densidadePixels: '264 PPI', brilho: 'Pico 1000nits', painel: 'LCD', coberturaVidro: '' },
        cameras: { traseira: '50MP com IA', frontal: '5MP com IA', modoDisparo: { traseira: 'Foto, Vídeo, Retrato, Noturno, PRO, Panorama, Time-Lapse, Adesivo, Alta Resolução, Hypertext, Google Lens | Principal: Grande Angular - 50MP; f/1,8; FOV 76°; lente 5P; compatível com Af | Sensor Flicker: 2MP; f/2,4; FOV 89°; lente 3P', frontal: 'Vídeo, Retrato, Noturno, Panorama, Time-Lapse, Adesivo, Retoque, Luz de Preenchimento de Tela, Alta Resolução | 5MP; f/2,2; FOV 77°; lente 3P' }, video: { traseira: '1080P 30fps, 720P 30fps | Compatível com filmagem de vídeo com zoom | Time-Lapse: 1080P 30fps', frontal: '1080P 30fps, 720P 30fps' } },
        processamento: { soc: 'Qualcomm® Snapdragon™ 6s gen 1', cpu: 'octa-core', gpu: 'Adreno™ 610 - 1050MHz' },
        bateria: { capacidade: '6000mAh', carregamentoRapido: '45W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Não suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor de proximidade', 'Acelerômetro', ' Sensor de impressão digital lateral', 'Indução geomagnética'],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/26/28 | LTE TDD: 38/40/41 | 4G móvel' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz | 1 x 1 SISO', versaoBluetooth: 'Bluetooth® 5.0, BLE', codecAudioBluetooth: 'SBC, AAC, aptx', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Não suportado' },
        sistemaOperacional: 'ColorOS 15.0 (Baseado em Android 15)',
        tecnologiaLocalizacao: { gnss: 'Banda simples: Beidou, GPS, GLONASS, Galileo, QZSS', outros: 'Banda simples: Beidou, GPS, GLONASS, Galileo, QZSS' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'a58',
      nome: 'OPPO A58',
      imagem: 'assets/img/a58.png',
      subtitulo: '16GB RAM (8+8) | 256GB Armazenamento',
      diferencial: 'Tela Sunlight FHD+ | Som estéreo',
      cameras: 'Traseira 50MP, Frontal 8MP',
      carregador: '33W SUPERVOOC',
      bateria: '5000mAh',
      processador: 'Mediatek® Helio™ G85',
      linha: 'linha-a',
      specs: {
        cores: 'Preto | Verde',
        dimensoesPeso: { altura: 'aprox. 165,65mm', largura: 'aprox. 75,98mm', espessura: 'aprox. 7,99mm', peso: 'cerca de 192g' },
        armazenamento: { ram: '16GB (8+8)', tipoRam: 'LPDDR4x', rom: '256GB', especificacoesRom: 'Emmc 5.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6,72"', proporcaoTela: '91,4%', resolucao: 'FHD+ (2400 x 1080)', taxaAtualizacao: '90Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 100% DCI-P3 | Modo Natural: 100% sRGB', profundidadeCor: '16,7 milhões de cores (8-bit)', densidadePixels: '391 PPI', brilho: 'Pico 680nits', painel: 'LCD (LTPS)', coberturaVidro: '' },
        cameras: { traseira: '50MP', frontal: '8MP', modoDisparo: { traseira: 'Noite, Vídeo, Foto, Retrato, Lapso de Tempo, PRO, Panorâmica, Adesivo e Google Lentes | Principal: 50MP; f/1.8; FOV 75.5°; lente 5P; AF suportado | Sensor Flicker: 2MP; f/2.4; FOV 89.1°; lente 3P; FF', frontal: 'Vídeo, Foto, Retrato, Lapso de Tempo, Panorâmica e Adesivo | 8MP; f/2.0; FOV 80°; lente 4P; FF' }, video: { traseira: '1080P - 30fps, 720P - 30fps | Modo Time-lapse: 1080P - 30fps', frontal: 'Até 1080 - 30fps, 720P - 30fps por padrão' } },
        processamento: { soc: 'Mediatek® Helio™ G85', cpu: 'octa-core', gpu: 'Mali G52 MC2™ 1000MHz' },
        bateria: { capacidade: '5000mAh', carregamentoRapido: '33W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor geomagnético', 'Sensor de luz', 'Sensor de proximidade', 'Acelerômetro', 'Sensor de gravidade', 'Contador de passos'],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/5/8 | LTE FDD: 1/3/5/7/8/20/28 | LTE TDD: 38/40/41 | 4G móvel' },
        conectividade: {wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz', versaoBluetooth: 'Bluetooth® 5.3, BLE', codecAudioBluetooth: 'SBC, AAC, aptX HD, LDAC', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Não suportado' },
        sistemaOperacional: 'ColorOS 13.1 (Baseado em Android 13)',
        tecnologiaLocalizacao: { gnss: 'Beidou: B11; GPS: L1; GLONASS: G1; Galileo: E1; QZSS: L1', outros: 'GPS Assistido (A-GPS); Posicionamento de rede WLAN e cellular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'a60',
      nome: 'OPPO A60',
      imagem: 'assets/img/a60.png',
      subtitulo: '16GB RAM (8+8) | 256GB Armazenamento',
      diferencial: 'Ultra resistência MIL-STD 810H',
      cameras: 'Traseira 50MP, Frontal 5MP',
      carregador: '45W SUPERVOOC',
      bateria: '5100mAh',
      processador: 'Qualcomm® Snapdragon™ 6s gen 1',
      linha: 'linha-a',
      specs: {
        cores: 'Preto | Branco | Vinho | Lilás',
        dimensoesPeso: { altura: 'aprox. 165.77mm', largura: 'aprox. 76.08mm', espessura: 'aprox. 7.68mm', peso: 'aprox. 186g' },
        armazenamento: { ram: '16GB (8+8)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'eMMC 5.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.67”', proporcaoTela: '89.9%', resolucao: 'HD+ (1604 x 720)', taxaAtualizacao: '90Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 83% NTSC | Modo Conforto: 71% NTSC', profundidadeCor: '16.7 milhões de cores (8-bit)', densidadePixels: '264 PPI', brilho: 'Pico: 1000nits', painel: 'LCD', coberturaVidro: 'China Southern Glass (duas vezes reforçado) | Panda (duas vezes reforçado)' },
        cameras: { traseira: '50MP', frontal: '5MP', modoDisparo: { traseira: 'Pro, Vídeo, Foto, Noite, Panorâmica, Slow motion, Time-lapse, Adesivo, Scanner de Texto, e Extra HD | Principal: 50MP; f/1.8; FOV 76°; Lente 5P; AF; motor de foco open-loop | Sensor Flicker: 2MP', frontal: 'Vídeo, Foto, Retrato, Noite, Panorâmica, Time-lapse, Adesivo, e Extra HD | 5MP; f/2.2, FOV 78°; Lente 3P; FF' }, video: { traseira: '1080P - 30fps, 720P - 30fps | Modo Time-lapse: 1080P - 30fps', frontal: 'Até 1080 - 30fps, 720P - 30fps por padrão' } },
        processamento: { soc: 'Qualcomm® Snapdragon™ 6s gen 1', cpu: 'octa-core', gpu: 'Adreno™ 610 - 1050MHz' },
        bateria: { capacidade: '5100mAh', carregamentoRapido: '45W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Não suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade', 'Pedômetro'],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/26/28 | LTE TDD: 38/40/41 | 4G móvel' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz', versaoBluetooth: 'Bluetooth® 5.0, BLE', codecAudioBluetooth: 'SBC, AAC, aptx', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Não suportado' },
        sistemaOperacional: 'ColorOS 14.0 (Baseado em Android 14)',
        tecnologiaLocalizacao: { gnss: 'BeiDou, GPS, GLONASS, Galileo e QZSS', outros: 'Single frequency: Positioning with A-GNSS, WLAN, and cellular data' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'a79',
      nome: 'OPPO A79',
      imagem: 'assets/img/a79.png',
      subtitulo: '16GB RAM (8+8) | 256GB Armazenamento',
      diferencial: 'Tecnologia 5G | NFC',
      cameras: 'Traseira 50MP, Frontal 5MP',
      carregador: '33W SUPERVOOC',
      bateria: '5000mAh',
      processador: 'Mediatek® Dimensity™ 6020',
      linha: 'linha-a',
      specs: {
        cores: 'Preto Mistério | Roxo Deslumbrante',
        dimensoesPeso: { altura: 'aprox. 165.6mm', largura: 'aprox. 76.0mm', espessura: 'aprox. 8,04', peso: 'aprox. 193g' },
        armazenamento: { ram: '16GB (8+8)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'UFS 2.2', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.72”', proporcaoTela: '91,4%', resolucao: 'FHD+ (2400 x 1080)', taxaAtualizacao: '90Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 96% NTSC | Modo Conforto: 71% NTSC', profundidadeCor: '16.7 milhões de cores (8-bit)', densidadePixels: '391 PPI', brilho: 'Pico: 680nits', painel: 'LCD (LTPS)', coberturaVidro: 'Panda Glass' },
        cameras: { traseira: '50MP', frontal: '8MP', modoDisparo: { traseira: 'Foto, vídeo, noturno, Pro, panorama, retrato, fotos por intervalos, câmera lenta, scanner de textos, extra HD, Sticker, e Google Lens | Principal: 50MP; f/1.8; FOV 77°; lente 5P; AF suportado | Sensor Flicker: 2MP; f/2.4; FOV 89°; lente 3P; FF', frontal: 'Foto, vídeo, panorama, retrato, noturno, Sticker, foto por intervalos, selfie com embelezamento, e compensação da exposição | 8MP; f/2.0; FOV 80°; Lente 4P; FF' }, video: { traseira: '1080P - 30fps, 720P - 30fps | Zoom de vídeo: 1080P - 30fps e 720P - 30fps | Time-lapse: 1080P - 30fps | Câmera lenta: 720P - 120fps', frontal: 'Máximo de 1080P/720P - 30fps, padrão de 720P - 30fps (função "embelezamento" ativada)' } },
        processamento: { soc: 'Mediatek® Dimensity™ 6020', cpu: 'octa-core', gpu: 'Mali-G57 MC2™ 950MHz' }, 
        bateria: { capacidade: '5000mAh', carregamentoRapido: '33W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade', 'Pedômetro'],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/66 | LTE TDD: 38/39/40/41 | 5G móvel: n1/n3/n5/n7/n8/n20/n28/n38/n40/n41/n66/n77/n78' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz', versaoBluetooth: 'Bluetooth® 5.3, BLE', codecAudioBluetooth: 'SBC, AAC, aptX, aptX HD e LDAC', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Suportado' },
        sistemaOperacional: 'ColorOS 13.1 (Baseado em Android 13)',
        tecnologiaLocalizacao: { gnss: 'Beidou: B11; GPS: L1; GLONASS: G1; Galileo: E1; QZSS: L1', outros: 'GPS Assistido (A-GPS); Posicionamento de rede WLAN e celular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'a5pro',
      nome: 'OPPO A5 Pro',
      imagem: 'assets/img/a5pro.png',
      subtitulo: '16GB RAM (8+8) | 256GB Armazenamento',
      diferencial: 'Resistência MIL-STD 810H | IP69',
      cameras: 'Traseira 50MP, Frontal 8MP',
      carregador: '45W SUPERVOOC',
      bateria: '5800mAh',
      processador: 'Mediatek® Dimensity™ 6300',
      linha: 'linha-a',
      specs: {
        cores: 'Marrom Chocolate | Rosa Pastel',
        dimensoesPeso: { altura: 'aprox. 164,82mm', largura: 'aprox. 75,53mm', espessura: 'aprox. 7,76', peso: 'aprox. 194g' },
        armazenamento: { ram: '16GB (8+8)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'UFS 2.2', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.67”', proporcaoTela: '89,9%', resolucao: 'HD+ (1604 x 720)', taxaAtualizacao: '120Hz', taxaAmostragemToque: 'Até 120Hz', gamaCores: 'Modo Vívido: 83% DCI-P3 | Modo Conforto: 100% sRGB', profundidadeCor: '16.7 milhões de cores (8-bit)', densidadePixels: '264 PPI', brilho: 'Pico: 1000nits', painel: 'LCD (LTPS)', coberturaVidro: 'Corning® Gorilla® Glass 7i | Xensation® α' },
        cameras: { traseira: '50MP com IA', frontal: '8MP com IA', modoDisparo: { traseira: 'Foto, Vídeo, Retrato, Noturno, PRO, Panorama, SLO-MO, Modo de Vídeo Duplo, Time-Lapse, Adesivo, Scanner de Documento, Google Lens | Principal: Grande Angular: 50 MP; f/1.8; FOV 76°; lente 5P; AF | Sensor Flicker: 2MP; f/2.4; FOV 88°; lente 3P', frontal: 'Foto, vídeo, panorama, retrato, noturno, Sticker, foto por intervalos, selfie com embelezamento, e compensação da exposição | 8 MP, f/2.0, FOV 80°; lente 4P' }, video: { traseira: '1080P - 30fps, 720P - 30fps | Zoom de vídeo: 1080P - 30fps e 720P - 30fps | Time-lapse: 1080P - 30fps | Câmera lenta: 720P - 120fps', frontal: 'Foto, Vídeo, Retrato, Noturno, Modo de Vídeo Duplo, Panorama, Time-Lapse, Adesivo, Retoque, Luz de preenchimento de tela' } },
        processamento: { soc: 'Mediatek® Dimensity™ 6300', cpu: 'octa-core', gpu: 'Mali-G57 MC2™ 1072MHz' },
        bateria: { capacidade: '5800mAh', carregamentoRapido: '45W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Lateral', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade' ],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/66 | LTE TDD: 38/39/40/41 | 5G móvel: n1/n3/n5/n7/n8/n20/n28/n38/n40/n41/n66/n77/n78' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz', versaoBluetooth: 'Bluetooth® 5.3, BLE', codecAudioBluetooth: 'SBC, AAC, aptX, aptX HD e LDAC', interfaceUsb: 'USB-C', conectorFoneOuvido: '3.5mm', nfc: 'Suportado' },
        sistemaOperacional: 'ColorOS 15.0 (Baseado em Android 15)',
        tecnologiaLocalizacao: { gnss: 'Beidou, GPS, GLONASS, Galileo, QZSS', outros: 'Suporta posicionamento assistido por A-GPS, posicionamento de LAN sem fio, posicionamento de rede cellular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'reno11f',
      nome: 'OPPO Reno11 F 5G',
      imagem: 'assets/img/reno11f.png',
      subtitulo: '16GB RAM (8+8) | 256GB Armazenamento',
      diferencial: 'Câmera ultra-nítida de 64MP com IA | Tela AMOLED',
      cameras: 'Traseira 64MP, Frontal 32MP',
      carregador: '67W SUPERVOOC',
      bateria: '5000mAh',
      processador: 'Mediatek® Dimensity™ 7050',
      linha: 'linha-reno',
      specs: {
        cores: 'Verde | Lilás',
        dimensoesPeso: { altura: 'aprox. 161,6mm', largura: 'aprox. 74,7mm', espessura: 'aprox. 7,54', peso: 'aprox. 177g' },
        armazenamento: { ram: '16GB (8+8)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'UFS 3.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.7”', proporcaoTela: '93,4%', resolucao: 'FHD+ (2412 x 1080)', taxaAtualizacao: '120Hz', taxaAmostragemToque: 'Até 240Hz', gamaCores: 'Modo Vívido: 100%  DCI-P3 | Modo Conforto: 100% sRGB', profundidadeCor: '1,07 Bilhão de cores (8-bit)', densidadePixels: '394 PPI', brilho: 'Pico: 1100nits', painel: '2.5D AMOLED flexível', coberturaVidro: 'Panda Glass (duas vezes reforçado)' },
        cameras: { traseira: '64 MP com IA', frontal: '32MP com IA', modoDisparo: { traseira: 'Pro, Vídeo, Foto, Retrato, Noite, Extra HD, Panorama, Macro, Câmera lenta, Lapso de tempo, Vídeo de visualização dupla, Sticker, Scanner de texto, Google Lens | Principal: 64 MP; f/1.7; FOV 81°; Lente 6P; AF suportado; OIS não suportado | Grande Angular: 8 MP; f/2.2; FOV 112°; Lente 5P; foco fixo | Macro: 2 MP; f/2.4; FOV 89°; Lente 3P+IR; foco fixo', frontal: 'Vídeo, Foto, Retrato, Noite, Panorama, Lapso de tempo, Vídeo de visualização dupla e Sticker | 32MP; f/2.4; FOV 90°; Lente 5P; AF não suportado' }, video: { traseira: '4K - 30fps, 1080P - 60fps/30fps, 720P - 60fps/30fps; Padrão: 1080P - 30fps | EIS: 1080P - 60fps/30fps | Câmera Lenta: 1080P - 120fps/480fps, 720P - 240fps/960fps', frontal: '4K/1080P/720P - 30fps; Padrão: 1080P - 30fps | Estabilização de Vídeo: 1080P - 30fps' } },
        processamento: { soc: 'Mediatek® Dimensity™ 7050', cpu: 'octa-core', gpu: 'ARM Mali-G68 MC4™ 950MHz' },
        bateria: { capacidade: '5000mAh', carregamentoRapido: '67W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Na tela', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade', 'Pedômetro' ],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/66 | LTE TDD: 38/39/40/41 | 5G móvel: n1/n3/n5/n7/n8/n20/n28/n38/n40/n41/n66/n77/n78' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 40Mhz/80Mhz | WLAN Display; WLAN tethering; Wi-Fi 5GHz 80MHz; 2×2 MIMO', versaoBluetooth: 'Bluetooth® 5.2, BLE', codecAudioBluetooth: 'SBC, AAC, aptX, aptX HD e LDAC', interfaceUsb: 'USB-C', conectorFoneOuvido: 'USB-C', nfc: 'Suportado' },
        sistemaOperacional: 'ColorOS 14.0 (Baseado em Android 14)',
        tecnologiaLocalizacao: { gnss: 'BeiDou: B1I; GPS: L1; GLONASS: G1; Galileo: E1; QZSS: L1', outros: 'GPS Assistido (A-GPS); Posicionamento de rede WLAN e celular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'reno13f',
      nome: 'OPPO Reno13 F 5G',
      imagem: 'assets/img/reno13f.png',
      subtitulo: '24GB RAM (12+12) | 256GB Armazenamento',
      diferencial: 'IP69 | Recursos de IA avançados',
      cameras: 'Traseira 50MP, Frontal 32MP',
      carregador: '45W SUPERVOOC',
      bateria: '5800mAh',
      processador: 'Qualcomm® Snapdragon™ 6 gen 1',
      linha: 'linha-reno',
      specs: {
        cores: 'Grafite | Lavanda',
        dimensoesPeso: { altura: 'aprox. 162,2mm', largura: 'aprox. 75,05mm', espessura: 'aprox. 7,76', peso: 'aprox. 192g' },
        armazenamento: { ram: '24GB (12+12)', tipoRam: ' LPDDR4X', rom: '256GB', especificacoesRom: 'UFS 3.1', microSD: 'Suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.67”', proporcaoTela: '92,2%', resolucao: 'FHD+ (2400 x 1080)', taxaAtualizacao: '120Hz', taxaAmostragemToque: 'Até 180Hz', gamaCores: 'Modo Vívido: 100%  DCI-P3 | Modo Conforto: 100% sRGB', profundidadeCor: '16.7 milhões de cores (8-bit)', densidadePixels: '394 PPI', brilho: 'Pico: 1200nits', painel: 'AMOLED Rígido', coberturaVidro: 'Asahi Glass® Dragontrail™ Star 2' },
        cameras: { traseira: '50MP com IA', frontal: '32MP com IA', modoDisparo: { traseira: 'Foto, Vídeo, Retrato, Noturno, PRO, Panorama, Slo-mo, Modo de Vídeo Duplo, Time-lapse, Adesivos, HI-RES, Google lens, Subaquático, Macro, Scanner de Documentos | Principal: 50 MP; f/1.8; FOV 78°; lente 5P; AF; OIS suportado | Grande Angular: 8MP; f/2.2; FOV 112°; lente 5P; EIS suportado | Macro: 2MP; f/2.4; FOV 89°', frontal: 'Foto, Vídeo, Retrato, Noturno, Panorama, Modo de Vídeo Duplo, Time-lapse, Adesivo, Retoque, Luz de Preenchimento na Tela | 32MP, f/2.4, FOV 82°; lente 5P' }, video: { traseira: '4K - 30fps, 1080P - 60fps/30fps, 720P - 60fps/30fps; Padrão: 1080P - 30fps | EIS/OIS: 1080P - 60fps/30fps 720P - 60fps/30fps | Zoom em Vídeo: 1080P - 60fps/30fps, 720P - 60fps/30fps, 4K - 30fps | Câmera Lenta: 720P - 240fps, 720p/1080P - 120fps | Time-lapse: 1080P - 30fps | Vídeo Duplo: 1080P - 30fps', frontal: '1080P/720P - 30fps; Padrão: 1080P - 30fps' } },
        processamento: { soc: 'Qualcomm® Snapdragon™ 6 gen 1', cpu: 'octa-core', gpu: 'Adreno™ 710™ 676MHz' },
        bateria: { capacidade: '5800mAh', carregamentoRapido: '45W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Na tela', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor Geomagnético', 'Sensor de Luz Amiente Frente/Trás', 'Sensor de Proximidade', 'Acelerômetro', 'Sensor de Gravidade' ],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/66 | LTE TDD: 38/39/40/41 | 5G móvel: n1/n3/n5/n7/n8/n20/n28/n38/n40/n41/n66/n77/n78' },
        conectividade: { wlan: 'Wi-Fi 5 (802.11ac), 802.11a/b/g/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 20Mhz/40Mhz/80Mhz | WLAN Display; WLAN tethering; 1 x 1 SISO', versaoBluetooth: 'Bluetooth® 5.1, BLE', codecAudioBluetooth: 'SBC, AAC, aptX, aptX HD e LDAC', interfaceUsb: 'USB-C', conectorFoneOuvido: 'USB-C', nfc: 'Suportado' },
        sistemaOperacional: 'ColorOS 15.0 (Baseado em Android 15)',
        tecnologiaLocalizacao: { gnss: 'Single band: Beidou, GPS, GLONASS, Galileo, QZSS', outros: 'Suporta os sistemas de posicionamento assistido A-GPS ,wireless LAN, cellular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
    new Smartphone({
      id: 'reno13',
      nome: 'OPPO Reno13 5G',
      imagem: 'assets/img/reno13.png',
      subtitulo: '24GB RAM (12+12) | 513GB Armazenamento',
      diferencial: 'IP69 | Recursos de IA avançados | 512GB de armazenamento',
      cameras: 'Traseira 50MP, Frontal 50MP',
      carregador: '80W SUPERVOOC',
      bateria: '5600mAh',
      processador: 'Mediatek® Dimensity™ 8350',
      linha: 'linha-reno',
      specs: {
        cores: 'Branco | Azul Indigo',
        dimensoesPeso: { altura: 'aprox. 157,9mm', largura: 'aprox. 74,73mm', espessura: 'aprox. 7,24', peso: 'aprox. 181g' },
        armazenamento: { ram: '24GB (12+12)', tipoRam: ' LPDDR5X', rom: '512GB', especificacoesRom: 'UFS 3.1', microSD: 'Não suportado', usbOtg: 'Suportado' },
        tela: { tamanho: '6.67”', proporcaoTela: '92,2%', resolucao: 'FHD+ (2400 x 1080)', taxaAtualizacao: '120Hz', taxaAmostragemToque: 'Até 240Hz', gamaCores: 'Modo Vívido: 100%  DCI-P3 | Modo Conforto: 100%  DCI-P3 | Modo Pro: 100%  DCI-P3', profundidadeCor: '1.07 bilhão de cores', densidadePixels: '460 PPI', brilho: 'Pico: 1200nits', painel: 'AMOLED Flexível', coberturaVidro: 'Corning® Gorilla® Glass 7i' },
        cameras: { traseira: '50 MP com IA', frontal: '50 MP com IA', modoDisparo: { traseira: 'Vídeo, Foto, Retrato, Noturno, Alta Resolução, PANO, Slo-mo, Time-lapse, Vídeo com Visão Dupla, Adesivos, subaquático, Scanner de Documentos, Googlen lens | Grande-Angular (principal): 50 MP; f/1.8; FOV 79°; lente 5P; AF; OIS suportado | Ultra grande angular: 8 MP; f/2.2; FOV 116°; lente 5P; AF suportado | Monocromática: 2 MP; f/2.4; FOV 89°; lente 3P', frontal: 'Vídeo, Foto, Retrato, Noturno, Alta Resolução, PANO, Time-lapse, Vídeo com Visão Dupla, Adesivos | 50 MP, f/2.0, FOV 90°; lente 5P; AF suportado' }, video: { traseira: '4K - 60fps/30fps, 1080P - 60fps/30fps, 720P - 60fps/30fps | EIS/OIS: 4K - 60fps/30fps, 1080P - 60fps/30fps,  720P - 30fps | Zoom em Vídeo: 4K - 60fps/30fps,1080P - 60fps/30fps, 720P - 60fps/30fps, 4K - 30fps | Câmera Lenta: 720P - 240fps,  1080P - 120fps | Time-lapse: 1080P - 30fps | Vídeo Duplo: 1080P - 30fps', frontal: 'Vídeo EIS: 4K - 60fps/30fps, 1080P/30fps (com retoque ativado), 720P 30fps | Zoom em Vídeo: Suportado | Modo Dual-view: Suportado' } },
        processamento: { soc: 'Mediatek® Dimensity™ 8350', cpu: 'octa-core', gpu: 'ARM Turse G615™' },
        bateria: { capacidade: '5600mAh', carregamentoRapido: '80W SUPERVOOC' },
        somm: '300% ultra-volume',
        estereo: 'Suportado',
        biometria: { impressaoDigital: 'Suportado | Na tela', reconhecimentoFacial: 'Suportado' },
        sensores: ['Sensor de Proximidade', 'Sensor de Luz Ambiente', 'Sensor de Temperatura de Cor', 'E-compass', 'Acelerômetro', 'Giroscópio', 'Controle remoto infravermelho' ],
        redeCelular: { sim: 'Duplo | Físico', tipoCartaoSim: 'Nano-SIM Card/Nano-USIM Card', bandasFrequencia: 'GSM: 850/900/1800/1900MHz | WCDMA: 1/2/4/5/6/8/19 | LTE FDD: 1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/66 | LTE TDD: 38/39/40/41 | 5G móvel: n1/n3/n5/n7/n8/n20/n28/n38/n40/n41/n66/n77/n78' },
        conectividade: { wlan: 'WiFi 6 (802.11ax), WiFi 5 (802.11ac), 802.11b/g/a/n | WLAN 2.4G 20Mhz/40Mhz | WLAN 5G 20Mhz/40Mhz/80Mhz | WLAN Display; WLAN tethering; 2 x 2 MIMO', versaoBluetooth: 'Bluetooth® 5.4, BLE', codecAudioBluetooth: 'SBC, AAC, aptx, aptx-HD, LDAC, LHDC5.0', interfaceUsb: 'USB-C', conectorFoneOuvido: 'USB-C', nfc: 'Suportado' },
        sistemaOperacional: 'ColorOS 15.0 (Baseado em Android 15)',
        tecnologiaLocalizacao: { gnss: 'Single band: Beidou, GPS, GLONASS, Galileo, QZSS', outros: 'Suporta os sistemas de posicionamento assistido A-GPS ,wireless LAN, cellular' },
        naCaixa: ['Smartphone', 'Carregador', 'Cabo USB', 'Capa protetora', 'Ferramenta ejetora de SIM', 'Guia rápido', 'Guia de segurança'],
      },
    }),
  ];

  constructor() { }

  getSmartphones(): Observable<Smartphone[]> {
    return of(this.allSmartphones);
  }

  // NOVO MÉTODO: getSmartphoneById
  getSmartphoneById(id: string): Observable<Smartphone | undefined> {
    const smartphone = this.allSmartphones.find(s => s.id === id);
    return of(smartphone);
  }
}
